#!/bin/bash
echo -e '\033]2;'NODE-Red console'\007'
echo " "
echo "Stop Node-RED"
echo " "
echo "Use  node-red-start                      to start Node-RED again"
echo "Use  sudo update-rc.d nodered defaults   to autostart Node-RED at every boot"
echo " "
sudo /etc/init.d/nodered stop
echo " "
exit
